// USER CONSTANTS
export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const USER_ERROR_OCCURED = "USER_ERROR_OCCURED";
export const USER_ERROR_REMOVED = "USER_ERROR_REMOVED";
